name: FTCcosmetics
version: 1.0
author: Wout
main: ftc.cosmetics.Main
description: Plugin that handles the cosmetics.
api-version: 1.16

commands:
  cosmetics:
    description: Opens the cosmetics tab.
  addparticle:
    description: Adds a particle to a player in the DataPlugin config.
  removeparticle:
    description: Removes a particle from a player in the DataPlugin config.
  addgems:
    description: Adds gems to a player in the DataPlugin config.
  getgems:
    description: Gets the amount of gems a player has.