name: Name									# Needs to change
version: 1.0
author: Wout, Botul
main: ftc.name.Main							# Needs to change
description: Plugin that does something!	# Needs to change
api-version: 1.16

commands:
  randomcommand:							# Needs to change
    description: descrip.					# Needs to change