name: FTCCore
version: @version@
main: net.forthecrown.core.FtcCore
api-version: 1.16
authors: [ Botul, Wout ]
loadbefore:
  - OpenInv
  - Essentials

commands:
  staffchat:
    permission: ftc.staffchat
    permission-message: You do not have permission to use this!
    description: The StaffChat command.
    aliases:
      - sc
    usage: 'ยง7Usage: /sc <message>'