main: ftc.staffchat.Main
name: StaffChatFTC
version: 1.0
api-version: 1.16
author: BotulToxin, Wout

commands:
  staffchat:
    description: "The command to use the Staff Chat"
    permission: ftc.staffchat
    permission-message: "You do not have permission!"
    aliases: sc
  staffchattoggle:
    description: "Enable/disable all messages being sent into StaffChat"
    permission: ftc.staffchat
    permission-message: "You do not have permission!"
    aliases: sct