name: Chat
version: 1.0
author: Wout, Botul
main: ftc.chat.Main
description: Plugin that manages all FTC message things!
api-version: 1.16

commands:
  bc:
    description: Broadcasts a message to every player online.
  aahelp:
    description: Displays the help message.
  discord:
    aliases: [disc]
    description: Displays the discord message.
  rlchat:
    description: Reloads the config file.
  findpost:
    aliases: [findpole]
    description: Finds the nearest regionpole based on your location.
  posthelp:
    aliases: [polehelp]
    description: Gives more information about regionpoles.
  spawn:
    description: Helps noobs go to spawn lol.
  tpask:
    aliases: [tpa]
    permission: ftc.tpa
    description: Request to teleport to another player.
  tpaskhere:
    aliases: [tpahere]
    permission: ftc.tpahere
    description: Request another player to teleport to you.
  mwah:
    aliases: [smooch, kiss]
    description: Sends a kiss to someone <3
  poke:
    description: Poke someone.
  bonk:
    description: Bonk someone.
  toggleemotes:
    description: Toggles emotes.
  sc:
    description: "The command to use the Staff Chat"
    permission: ftc.staffchat
    permission-message: "You do not have permission to do this."
    aliases: staffchat
  sct:
    description: "Enable/disable all messages being sent into StaffChat"
    permission: ftc.staffchat
    permission-message: "You do not have permission to do this."
    aliases: staffchattoggle