DelayBetweenAnnouncements: 12000
Prefix: '&6[FTC]&r '
Announcements:
  - 'To visit a region, do &e/visit &rwhen you are near a region pole.'
  - 'Please use the Resource World in Hazelguard if you need a lot of materials.'
  - 'You can find more information about &e/ranks &rin the shop.'
  - 'If you want others to know you are afk, type &e/afk&r.'
  - 'If you like a challenge, you can try to complete &ethe Dungeons&r. Follow the signs in Hazelguard.'
  - 'Remember, there are item shops in Hazelguard.'
  - 'If you want to, you can join us on &e/discord&r.'
  - 'There is a skeleton farm in Hazelguard if you need xp or bones.'
  - 'Type &e/findpole &rto find the closest regionpole.'
  - 'You can get the Knight tag and a &eRoyal Sword&r for completing the Dungeons.'
  - 'You can do &e/polehelp &rif you need some help with regionpoles.'
  - 'You can &e/vote&r for a chance to grab as much items as you can in the &eBank Vault&r!'
  - '&eThe End &ris only open the first 7 days of every month, it closes and resets again after.'
  - 'If you would like to support the server, consider checking the server &e/shop&r and &e/patreon&r.'
  #- 'The player with the most enderman kills will get the &eCrown &rat the end of endweek.'
Discord: 'Join our discord server:&b https://discord.gg/wXjHNdp'
NoEmotes: []
PlayersWithSCT: []