name: BigCrownEvent
version: 1.0
author: Wout, Botul
main: ftc.bigcrown.Main	
description: Plugin for the last crown event in 2020.
api-version: 1.16

commands:
  BigBootyEvent:
    description: "I'm just luring you on with the name, I still despise this meme lol"
    aliases:
      - bbe
      - bigbootyevent
    permission: bbe.admin
    permission-message: "You do not have permission to use this command"
  capturepoint:
    description: "This was such a mess to make jesus"
    permission: bbe.admin