name: Dungeons
version: ${project.version}
main: net.forthecrown.dungeons.Dungeons
api-version: 1.16
authors: [ Wout ]
depend:
  - FTCCore

commands:
  rankadd:
    description: adds a rank.
  rankremove:
    description: removes a rank.
  addlore:
    description: adds lore.
