name: RandomFeatures
version: 2.0
author: Wout
main: me.wout.RandomFeatures.Main
description: Plugin with random custom features used on FTC.
api-version: 1.16

commands:
  grave:
    aliases: [gr]
    description: Opens the grave of a player if they have one.
  wild:
    description: Teleports you to a random location in the resource world.
  crowntop:
    description: Shows the crown competition leaderboard.
  deathtop:
    description: Shows the death leaderboard.
  christmasgift:
    description: Command to give christmasgift.