Prefix: '&6[FTC]&r '
Discord: 'Join our discord server:&b https://discord.gg/wXjHNdp'
Day: 1

ServerSpawn:
  ==: org.bukkit.Location
  world: world
  x: 153.5
  y: 5
  z: 353.5
  pitch: 0
  yaw: 90

System:
  save-periodically: true
  save-interval-mins: 60
  run-deleter-on-startup: true