name: ShopsReworked
version: 2.0
author: Wout
main: me.wout.shopsreworked.main
description: Wout's plugin that handles shops on For The Crown server.
api-version: 1.15

commands:
  bank:
    aliases: [money, bal, balance]
    description: Shows your current balance.
  pay:
    description: Pays another player.
  givecash:
    aliases: [givemoney, addcash, addmoney, addbal, addbalance]
    description: Creates money for a player.
  setcash:
    aliases: [setmoney, setbal, setbalance, balset]
    description: Sets the amount of money for a player.
  shop:
    description: Opens the FTC shop menu.
  baltop:
    description: Shows the 5 richest players.