name: DataPlugin
version: 2.0
author: Wout
main: ftc.dataplugin.DataPlugin
description: Plugin that does the data stuff.
api-version: 1.16
depend:
  - CrownEventAPI
commands:
  addrank:
    permission: ftc.addrank
    description: Adds a rank to a player in the config.
  removerank:
    permission: ftc.removerank
    description: Removes a rank from a player in the config.
  listrank:
    permission: ftc.listrank
    description: Lists a rank of a player in the config.
  canswapbranch:
    permission: ftc.canswapbranch
    description: Shows if a player can swap branches according to in the config.
  setswapbranch:
    permission: ftc.setswapbranch
    description: Sets canswapbranch to true or false for a player in the config.
  setbranch:
    permission: ftc.setbranch
    description: Sets branch of a player if canswapbranch is true in the config.
  getbranch:
    permission: ftc.getbranch
    description: Gets branch of a player in the config.
  rank:
    aliases: [ranks]
    description: Shows the rank gui.
  makebaron:
    permission: ftc.makebaron
    description: Isn't it obvious?
  addpet:
    permission: ftc.addpet
    description: Adds a pet to the list of pets of a player.
  commandun:
    description: First option for Jerome.
  commanddeux:
    description: Second option for Jeromre.