Day: 1
HeadChestLocation1:
  world: world
  x: 45
  y: 17
  z: -30
HeadChestLocation2:
  world: world
  x: 46
  y: 17
  z: -30
HeadChestLocation3:
  world: world
  x: 47
  y: 17
  z: -30
HeadChestLocation4:
  world: world
  x: 48
  y: 17
  z: -30
ChosenHead: 'empty'
PlayerWhoSoldHeadAlready: []

Auctions:
  ExpirationTime: 604800000
  PickUpTime: 259200000

TreasureLoc:
  world: world
  x: 0
  y: 45
  z: 0
TreasureCommonLoot:
  world: world
  x: 46
  y: 17
  z: 4
TreasureRareLoot:
  world: world
  x: 46
  y: 17
  z: 6
TreasureSpecialLoot:
  world: world
  x: 46
  y: 17
  z: 8
PlayerWhoFoundTreasureAlready: []
Week: 1
ChosenDayForTrader: 1