name: Halloween
version: 1.0
author: Wout
main: me.wout.halloween.main
description: Wout's plugin that handles october crown event on For The Crown server.
api-version: 1.16

commands:
  itemlist:
    description: Displays all items that give points.
  leave:
    description: Let's you turn back to the overworld.