lists:
  quitPlayers: []
  disqualifiedPlayers: []
lobby-location:
start-location:
king: 'FTCempty'

settings:
  remove-on-quit: true
  remove-on-shutdown: true
  cumulative-points: false
  to-spawn-on-end: true
  timed-event: false
messages:
  prefix: "&6[FTC] &r"
  too-little-args: "&4Too little arguments!"
  invalid-arg: "&4Invalid argument!"
  entry-disallowed: "&4&lHey! &7You are not allowed to enter the event!"
  disqualify: "&7You have been disqualified from the event!"
  undisqualify: "&7You are now allowed to participate in Crown Events again!"
  sender-disqualify: "&4%NAME% &7is no longer allowed to participate in Crown Events!"
  sender-undisqualify: "&4%NAME% &7is now allowed to participate in Crown Events!"
  removed-for-leaving: "&7Your event was disrupted :("
  king: "&e&lCongratulations! &7You have been made&r &l&f[&e&l%TITLE%&r&l] &7for winning the Crown Event!"
  sender-king: "&7%NAME% has been made&r &l&f[&e&l%TITLE%&r&l]"
  king-removed: "The previous king/queen has been removed!"
  king-already-exists: "&7A king already exists!"
  timer-finish: "&7You finished in &e%TIMELEFT%!"
  timeleft-finish: "&7You finished with &e%TIMELEFT% &7remaining!"
  score-finish: "&7You finished with a score of &e%SCORE%!"
  plugin-reloaded: "The plugin has been reloaded!"