name: CrownEventAPI
version: ${project.version}
main: ftc.crownapi.Main
api-version: 1.16
author: BotulToxin

commands:
  crownapi:
    permission-message: "You do not have permission to use this!"
    permission: crownapi.admin
    description: "The CrownEventAPI Command"