name: CrownEventAPI
version: ${project.version}
main: ftc.crownapi.EventApi
api-version: 1.16
author: BotulToxin

commands:
  crownapi:
    permission: crownapi.admin
    permission-message: "You do not have permission to use this command!"
    description: "The CrownEventAPI Command."
  disqualify:
    permission: crownapi.admin
    permission-message: "You do not have permission to use this command!"
    description: "Disqualifies a player from participating in the event."
  kingmaker:
    permission: crownapi.kingmaker
    permission-message: "You do not have permission to use this command!"
    description: "Makes a player a king, or removes the current king."